name: Herring Cove
author: Herring Cove
##baseurl: /david8388.github.io
description: theme for jekyll
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
timezone: Asia/Taipei
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

highlighter: pygments
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
