name: David
author: David
##baseurl: /david8388.github.io
description: 全端工程師的學習筆記
github: https://github.com/david8388
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: hsienwu830808@gmail.com
timezone: Asia/Taipei
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

highlighter: rouge
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
